#!/bin/sh

sudo rsync -av --progress --exclude='.git' --update ./ /etc/nixos/

cd /etc/nixos
sudo nixos-rebuild switch --flake /etc/nixos
sudo nix-collect-garbage --delete-older-than 14d
sudo nix-store --gc