#!/bin/sh

sudo rsync -av --progress --exclude='.git' --update ./ /etc/nixos/

cd /etc/nixos
sudo nix flake update
sudo nixos-rebuild switch --flake /etc/nixos
sudo nix-collect-garbage --delete-older-than 30d