#!/bin/sh
echo "OLD! Use yonix!"


sudo rm -rf /etc/nixos/
sudo mkdir /etc/nixos
sudo rsync -av --progress --exclude='.git' --update ./ /etc/nixos/

read -p "Enter hostname: " hostname
sudo hostname $hostname

cd /etc/nixos
sudo nixos-rebuild switch --flake .
